In [1]:
import pandas as pd
import numpy as np

Load Data

In [5]:
df = pd.read_csv("D3_student_placement_prediction_dataset_2026 (1).csv")

df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   student_id                 100000 non-null  int64
 1   age                        100000 non-null  int64
 2   gender                     100000 non-null  object
 3   cgpa                       100000 non-null  float64
 4   branch                     100000 non-null  object
 5   college_tier               100000 non-null  object
 6   internships_count          100000 non-null  int64
 7   projects_count             100000 non-null  int64
 8   certifications_count       100000 non-null  int64
 9   coding_skill_score         100000 non-null  float64
 10  aptitude_score             100000 non-null  float64
 11  communication_skill_score  100000 non-null  float64
 12  logical_reasoning_score    100000 non-null  float64
 13  hackathons_participated    100000 non-null  int64
 14  github_repos               100000 non-null  int64
 15  linkedin_connections       100000 non-null  int64
 16  mock_interview_score       100000 non-null  float64
 17  attendance_percentage      100000 non-null  float64
 18  backlogs                   100000 non-null  int64
 19  extracurricular_score      100000 non-null  float64
 20  leadership_score           100000 non-null  float64
 21  volunteer_experience       100000 non-null  object
 22  sleep_hours                100000 non-null  float64
 23  study_hours_per_day        100000 non-null  float64
 24  placement_status           100000 non-null  object
 25  salary_package_lpa         100000 non-null  float64
dtypes: float64(12), int64(9), object(5)
memory usage: 19.8+ MB

,student_id,age,cgpa,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,communication_skill_score,logical_reasoning_score,...,github_repos,linkedin_connections,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,sleep_hours,study_hours_per_day,salary_package_lpa
count,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,21.005740,7.496890,1.50223,3.001860,2.005150,69.825326,64.988108,67.960744,65.931696,...,4.005160,524.559110,69.989411,84.730169,0.497590,59.894049,54.937526,6.983319,3.523124,7.252106
std,28867.657797,1.999562,0.992834,1.22528,1.731764,1.416553,14.694618,14.844093,13.846636,14.826790,...,2.004897,274.993479,11.937257,9.416075,0.708434,19.549666,19.781197,1.468113,1.471248,6.735132
min,1.000000,18.000000,4.500000,0.00000,0.000000,0.000000,20.000000,20.000000,20.000000,20.000000,...,0.000000,50.000000,20.000000,50.000000,0.000000,0.000000,0.000000,3.000000,0.500000,0.000000
25%,25000.750000,19.000000,6.820000,1.00000,2.000000,1.000000,59.807945,54.894600,58.587535,55.940547,...,3.000000,287.000000,61.973172,78.325833,0.000000,46.538590,41.432390,6.000000,2.500000,0.000000
50%,50000.500000,21.000000,7.500000,1.00000,3.000000,2.000000,70.006250,65.011394,67.973221,66.003829,...,4.000000,523.000000,70.026665,85.018828,0.000000,60.079021,55.076210,7.000000,3.500000,11.100000
75%,75000.250000,23.000000,8.180000,2.00000,4.000000,3.000000,80.058762,75.079266,77.503749,76.113705,...,5.000000,764.000000,78.122083,91.782511,1.000000,73.549567,68.530115,8.000000,4.500000,13.470000
max,100000.000000,24.000000,10.000000,8.00000,13.000000,11.000000,100.000000,100.000000,100.000000,100.000000,...,16.000000,999.000000,100.000000,100.000000,6.000000,100.000000,100.000000,10.000000,10.000000,20.440000

ตรวจ Missing Values

In [6]:
df.isnull().sum()

student_id                   0
age                          0
gender                       0
cgpa                         0
branch                       0
college_tier                 0
internships_count            0
projects_count               0
certifications_count         0
coding_skill_score           0
aptitude_score               0
communication_skill_score    0
logical_reasoning_score      0
hackathons_participated      0
github_repos                 0
linkedin_connections         0
mock_interview_score         0
attendance_percentage        0
backlogs                     0
extracurricular_score        0
leadership_score             0
volunteer_experience         0
sleep_hours                  0
study_hours_per_day          0
placement_status             0
salary_package_lpa           0
dtype: int64

แก้ Data Format

In [10]:
for col in df.columns:
    if df[col].dtype == 'object':
        try:
            df[col] = pd.to_numeric(df[col])
        except:
            pass

ทำข้อมูลให้ Consistent

In [11]:
if 'gender' in df.columns:
    df['gender'] = df['gender'].str.lower()

Encoding (Categorical → Numeric)

In [12]:
df = pd.get_dummies(df, drop_first=True)

จัดการ Outliers (IQR)

In [13]:
numeric_cols = df.select_dtypes(include=['int64','float64']).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[col] = np.where(df[col] < lower, lower, df[col])
    df[col] = np.where(df[col] > upper, upper, df[col])

ลบ Column ที่ไม่จำเป็น

In [14]:
if 'id' in df.columns:
    df.drop('id', axis=1, inplace=True)

ดูข้อมูลที่ clean แล้ว

In [16]:
df

,student_id,age,cgpa,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,communication_skill_score,logical_reasoning_score,...,gender_male,branch_Civil,branch_ECE,branch_EEE,branch_IT,branch_Mechanical,college_tier_Tier 2,college_tier_Tier 3,volunteer_experience_Yes,placement_status_Placed
0,1.0,24.0,7.53,3.5,6.0,1.0,99.238568,81.707722,57.707166,59.070073,...,True,False,False,False,True,False,True,False,True,False
1,2.0,21.0,7.92,1.0,3.0,6.0,80.966123,63.116715,59.197085,78.976419,...,True,False,False,False,False,False,True,False,False,False
2,3.0,22.0,8.60,0.0,1.0,1.0,49.177184,48.658753,92.104885,80.603331,...,False,False,False,True,False,False,False,False,False,True
3,4.0,24.0,6.68,0.0,2.0,2.0,79.359084,66.376653,83.411798,64.187246,...,True,False,False,False,False,False,False,False,True,False
4,5.0,20.0,8.43,1.0,4.0,3.0,65.018573,61.274985,88.956331,56.163678,...,False,False,False,False,True,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996.0,21.0,7.97,0.0,3.0,5.0,71.483407,56.904150,87.245760,43.013761,...,True,False,False,False,False,True,True,False,True,True
99996,99997.0,18.0,7.79,1.0,1.0,2.0,78.960574,55.729008,42.767277,62.381626,...,False,False,False,False,False,False,False,False,True,False
99997,99998.0,20.0,6.71,2.0,4.0,4.0,66.691775,48.725390,72.394081,70.888580,...,False,False,False,False,True,False,True,False,True,True
99998,99999.0,19.0,7.21,2.0,3.0,0.0,67.214893,79.336599,45.375535,52.091126,...,False,False,False,False,False,False,True,False,False,False
99999,100000.0,22.0,8.58,1.0,3.0,2.0,92.146277,89.261932,81.629165,94.963205,...,False,False,True,False,False,False,False,True,True,True

ดูโครงสร้าง (Check missing, Datatype)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   student_id                 100000 non-null  float64
 1   age                        100000 non-null  float64
 2   cgpa                       100000 non-null  float64
 3   internships_count          100000 non-null  float64
 4   projects_count             100000 non-null  float64
 5   certifications_count       100000 non-null  float64
 6   coding_skill_score         100000 non-null  float64
 7   aptitude_score             100000 non-null  float64
 8   communication_skill_score  100000 non-null  float64
 9   logical_reasoning_score    100000 non-null  float64
 10  hackathons_participated    100000 non-null  float64
 11  github_repos               100000 non-null  float64
 12  linkedin_connections       100000 non-null  float64
 13  mock_interview_score       100000 non-null  float64
 14  attendance_percentage      100000 non-null  float64
 15  backlogs                   100000 non-null  float64
 16  extracurricular_score      100000 non-null  float64
 17  leadership_score           100000 non-null  float64
 18  sleep_hours                100000 non-null  float64
 19  study_hours_per_day        100000 non-null  float64
 20  salary_package_lpa         100000 non-null  float64
 21  gender_male                100000 non-null  bool
 22  branch_Civil               100000 non-null  bool
 23  branch_ECE                 100000 non-null  bool
 24  branch_EEE                 100000 non-null  bool
 25  branch_IT                  100000 non-null  bool
 26  branch_Mechanical          100000 non-null  bool
 27  college_tier_Tier 2        100000 non-null  bool
 28  college_tier_Tier 3        100000 non-null  bool
 29  volunteer_experience_Yes   100000 non-null  bool
 30  placement_status_Placed    100000 non-null  bool
dtypes: bool(10), float64(21)
memory usage: 17.0 MB

ดูสถิติ

In [18]:
df.describe()

,student_id,age,cgpa,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,communication_skill_score,logical_reasoning_score,...,github_repos,linkedin_connections,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,sleep_hours,study_hours_per_day,salary_package_lpa
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,50000.500000,21.005740,7.497559,1.444785,2.98441,1.999550,69.839640,64.998697,67.974065,65.943709,...,3.971250,524.559110,70.004361,84.740495,0.487955,59.906991,54.939768,6.983319,3.521380,7.252106
std,28867.657797,1.999562,0.990918,1.090353,1.68101,1.397523,14.652062,14.813881,13.807162,14.792256,...,1.917963,274.993479,11.892262,9.384284,0.674208,19.512267,19.775014,1.468113,1.466015,6.735132
min,1.000000,18.000000,4.780000,0.000000,0.00000,0.000000,29.431720,24.617601,30.213215,25.680810,...,0.000000,50.000000,37.749806,58.140816,0.000000,6.022126,0.785802,3.000000,0.500000,0.000000
25%,25000.750000,19.000000,6.820000,1.000000,2.00000,1.000000,59.807945,54.894600,58.587535,55.940547,...,3.000000,287.000000,61.973172,78.325833,0.000000,46.538590,41.432390,6.000000,2.500000,0.000000
50%,50000.500000,21.000000,7.500000,1.000000,3.00000,2.000000,70.006250,65.011394,67.973221,66.003829,...,4.000000,523.000000,70.026665,85.018828,0.000000,60.079021,55.076210,7.000000,3.500000,11.100000
75%,75000.250000,23.000000,8.180000,2.000000,4.00000,3.000000,80.058762,75.079266,77.503749,76.113705,...,5.000000,764.000000,78.122083,91.782511,1.000000,73.549567,68.530115,8.000000,4.500000,13.470000
max,100000.000000,24.000000,10.000000,3.500000,7.00000,6.000000,100.000000,100.000000,100.000000,100.000000,...,8.000000,999.000000,100.000000,100.000000,2.500000,100.000000,100.000000,10.000000,7.500000,20.440000

In [19]:
print("Missing:\n", df.isnull().sum())
print("Duplicates:", df.duplicated().sum())

Missing:
 student_id                   0
age                          0
cgpa                         0
internships_count            0
projects_count               0
certifications_count         0
coding_skill_score           0
aptitude_score               0
communication_skill_score    0
logical_reasoning_score      0
hackathons_participated      0
github_repos                 0
linkedin_connections         0
mock_interview_score         0
attendance_percentage        0
backlogs                     0
extracurricular_score        0
leadership_score             0
sleep_hours                  0
study_hours_per_day          0
salary_package_lpa           0
gender_male                  0
branch_Civil                 0
branch_ECE                   0
branch_EEE                   0
branch_IT                    0
branch_Mechanical            0
college_tier_Tier 2          0
college_tier_Tier 3          0
volunteer_experience_Yes     0
placement_status_Placed      0
dtype: int64
Duplicates: 0